# Site settings
title: Summer of Code
email: rocio.paez@me.com
description: <a href=http://teams.railsgirlssummerofcode.org/teams/17>Rails Summer of Code.</a>
baseurl: ""
url: "http://migraine.io"

# Build settings
markdown: kramdown
permalink: blog/:year/:title.html      #pretty
port: 4001
